# Generated by Django 4.2.27 on 2026-02-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["user", "is_default"], name="customer_po_user_id_314153_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(
                fields=["user", "created_at"], name="customer_po_user_id_bad264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="customer_po_user_id_14230d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="customer_po_user_id_f8eb6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_no"], name="customer_po_order_n_8bf8bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["order", "created_at"], name="customer_po_order_i_f32926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="customer_po_event_t_15ccc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["order", "created_at"], name="customer_po_order_i_f1d4f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["order", "status"], name="customer_po_order_i_3158cb_idx"
            ),
        ),
    ]
