# Generated by Django 4.2.28 on 2026-02-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "customer_portal",
            "0002_customeraddress_customer_po_user_id_314153_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("COMPLAINT", "COMPLAINT"),
                            ("SUGGESTION", "SUGGESTION"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("ONLINE_SERVICE", "ONLINE_SERVICE"),
                            ("ORDER_SERVICE", "ORDER_SERVICE"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField()),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("PROCESSING", "PROCESSING"),
                            ("CLOSED", "CLOSED"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customer_portal.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="customer_po_user_id_75a5c2_idx",
                    ),
                    models.Index(
                        fields=["feedback_type", "created_at"],
                        name="customer_po_feedbac_3f89b9_idx",
                    ),
                    models.Index(
                        fields=["target_type", "created_at"],
                        name="customer_po_target__488a07_idx",
                    ),
                ],
            },
        ),
    ]
