# Generated by Django 4.2.27 on 2026-02-19 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_portal", "0005_customerconversationmemory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("assistant", "assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("run_id", models.UUIDField(blank=True, null=True)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="customer_po_user_id_45dd21_idx",
                    ),
                    models.Index(
                        fields=["user", "run_id", "created_at"],
                        name="customer_po_user_id_d825f2_idx",
                    ),
                ],
            },
        ),
    ]
