# Generated by Django 4.2.28 on 2026-02-24 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_portal", "0006_customerchatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerModelProviderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("OPENAI_COMPAT", "OPENAI_COMPAT")],
                        default="OPENAI_COMPAT",
                        max_length=32,
                    ),
                ),
                ("api_base_url", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=128)),
                ("api_key_ciphertext", models.TextField()),
                ("api_key_masked", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=False)),
                ("extra_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="customer_po_user_id_6712e4_idx",
                    ),
                    models.Index(
                        fields=["user", "updated_at"],
                        name="customer_po_user_id_429d5b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customermodelproviderprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="portal_provider_profile_user_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="customermodelproviderprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="portal_provider_profile_single_active_uniq",
            ),
        ),
    ]
