# Generated by Django 4.2.28 on 2026-02-26 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_portal", "0007_customermodelproviderprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=32)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("selected", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "selected", "updated_at"],
                        name="customer_po_user_id_e5fe8c_idx",
                    ),
                    models.Index(
                        fields=["user", "updated_at"],
                        name="customer_po_user_id_029843_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customercartitem",
            constraint=models.UniqueConstraint(
                fields=("user", "sku"), name="portal_cart_user_sku_uniq"
            ),
        ),
    ]
