# Generated by Django 4.2.28 on 2026-02-26 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_portal", "0008_customercartitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ORDER", "ORDER"),
                            ("PAYMENT", "PAYMENT"),
                            ("ADDRESS", "ADDRESS"),
                            ("FEEDBACK", "FEEDBACK"),
                            ("PROFILE", "PROFILE"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "INFO"),
                            ("SUCCESS", "SUCCESS"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                        ],
                        default="INFO",
                        max_length=16,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("ORDER", "ORDER"),
                            ("FEEDBACK", "FEEDBACK"),
                            ("PROFILE", "PROFILE"),
                            ("ADDRESS", "ADDRESS"),
                            ("CHAT", "CHAT"),
                            ("NONE", "NONE"),
                        ],
                        default="NONE",
                        max_length=16,
                    ),
                ),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("target_route", models.CharField(blank=True, max_length=255)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="customer_po_user_id_6d2b45_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="customer_po_user_id_152e3f_idx",
                    ),
                ],
            },
        ),
    ]
