global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "admission_api"
    static_configs:
      - targets: ["admission_api:8000"]
