# Generated by Django 4.2.27 on 2025-12-29 07:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('CONFIRMED', 'CONFIRMED'), ('DISPATCHED', 'DISPATCHED'), ('DELIVERING', 'DELIVERING'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], max_length=32)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DELIVERY_DELAY', 'DELIVERY_DELAY'), ('SERVICE_ISSUE', 'SERVICE_ISSUE'), ('GAS_LEAK', 'GAS_LEAK'), ('REFUND', 'REFUND'), ('OTHER', 'OTHER')], max_length=32)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('ASSIGNED', 'ASSIGNED'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_provider', models.CharField(choices=[('OPENAI', 'OPENAI'), ('ANTHROPIC', 'ANTHROPIC'), ('LOCAL', 'LOCAL')], max_length=16)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField()),
                ('state', models.CharField(choices=[('INIT', 'INIT'), ('PLANNING', 'PLANNING'), ('VALIDATE', 'VALIDATE'), ('EXEC_TOOL', 'EXEC_TOOL'), ('RESPOND', 'RESPOND'), ('DONE', 'DONE'), ('ERROR', 'ERROR'), ('TOOL_EXEC', 'TOOL_EXEC'), ('FALLBACK', 'FALLBACK')], max_length=32)),
                ('input_json', models.JSONField(blank=True, null=True)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=64, null=True)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('policy_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agentrun')),
            ],
        ),
    ]
